name: Multi-Distro Test

on: [push]

jobs:
  test:
    runs-on: [self-hosted, linux, x64]
    strategy:
      matrix:
        image:
          - ubuntu:24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test in container
        run: |
          echo "🚀 Starting test in ${{ matrix.image }}"

          docker run --rm -i \
            --privileged \
            -v "$PWD":/workspace \
            -w /workspace \
            ${{ matrix.image }} bash -c "
              apt update &&
              apt install -y nftables git curl python3 python3-pip python3-scapy iproute2 bc &&
              python3 .tests/tests.py
            "